var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/unauthorized/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__2ffba720._.js")
R.c("server/chunks/ssr/node_modules_8c3db903._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ed0865a8._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/src_daaa8d64._.js")
R.c("server/chunks/ssr/src_app_error_tsx_ef715cc8._.js")
R.c("server/chunks/ssr/src_ec68d808._.js")
R.c("server/chunks/ssr/_5e4ee9d5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__d019a9b5._.js")
R.c("server/chunks/ssr/_cd591a15._.js")
R.c("server/chunks/ssr/_8e886a03._.js")
R.m(77240)
R.m(38911)
module.exports=R.m(38911).exports
