// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/ai-recommend" | "/error/401" | "/error/403" | "/error/404" | "/error/500" | "/login" | "/mate" | "/mate/[mateId]" | "/mate/write" | "/mypage" | "/mypage/reservations" | "/mypage/reviews" | "/mypage/settings" | "/owner/comments" | "/owner/dashboard" | "/owner/hidden" | "/owner/reservations" | "/owner/reviews" | "/owner/settings" | "/owner/themes" | "/owner/themes/create" | "/reservation" | "/reservation/complete" | "/reviews" | "/signup" | "/themes" | "/themes/[themeId]" | "/unauthorized"
type PageRoutes = never
type LayoutRoutes = "/" | "/owner"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/ai-recommend": {}
  "/error/401": {}
  "/error/403": {}
  "/error/404": {}
  "/error/500": {}
  "/login": {}
  "/mate": {}
  "/mate/[mateId]": { "mateId": string; }
  "/mate/write": {}
  "/mypage": {}
  "/mypage/reservations": {}
  "/mypage/reviews": {}
  "/mypage/settings": {}
  "/owner": {}
  "/owner/comments": {}
  "/owner/dashboard": {}
  "/owner/hidden": {}
  "/owner/reservations": {}
  "/owner/reviews": {}
  "/owner/settings": {}
  "/owner/themes": {}
  "/owner/themes/create": {}
  "/reservation": {}
  "/reservation/complete": {}
  "/reviews": {}
  "/signup": {}
  "/themes": {}
  "/themes/[themeId]": { "themeId": string; }
  "/unauthorized": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/owner": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
