// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/ai-recommend/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-recommend">> = Specific
  const handler = {} as typeof import("../../src/app/ai-recommend/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/error/401/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error/401">> = Specific
  const handler = {} as typeof import("../../src/app/error/401/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/error/403/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error/403">> = Specific
  const handler = {} as typeof import("../../src/app/error/403/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/error/404/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error/404">> = Specific
  const handler = {} as typeof import("../../src/app/error/404/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/error/500/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error/500">> = Specific
  const handler = {} as typeof import("../../src/app/error/500/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mate/[mateId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mate/[mateId]">> = Specific
  const handler = {} as typeof import("../../src/app/mate/[mateId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mate">> = Specific
  const handler = {} as typeof import("../../src/app/mate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mate/write/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mate/write">> = Specific
  const handler = {} as typeof import("../../src/app/mate/write/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mypage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage">> = Specific
  const handler = {} as typeof import("../../src/app/mypage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mypage/reservations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/reservations">> = Specific
  const handler = {} as typeof import("../../src/app/mypage/reservations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mypage/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/mypage/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mypage/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mypage/settings">> = Specific
  const handler = {} as typeof import("../../src/app/mypage/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/comments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/comments">> = Specific
  const handler = {} as typeof import("../../src/app/owner/comments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/owner/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/hidden/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/hidden">> = Specific
  const handler = {} as typeof import("../../src/app/owner/hidden/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/reservations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/reservations">> = Specific
  const handler = {} as typeof import("../../src/app/owner/reservations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/owner/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/settings">> = Specific
  const handler = {} as typeof import("../../src/app/owner/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/themes/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/themes/create">> = Specific
  const handler = {} as typeof import("../../src/app/owner/themes/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/themes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/themes">> = Specific
  const handler = {} as typeof import("../../src/app/owner/themes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reservation/complete/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reservation/complete">> = Specific
  const handler = {} as typeof import("../../src/app/reservation/complete/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reservation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reservation">> = Specific
  const handler = {} as typeof import("../../src/app/reservation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/themes/[themeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/themes/[themeId]">> = Specific
  const handler = {} as typeof import("../../src/app/themes/[themeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/themes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/themes">> = Specific
  const handler = {} as typeof import("../../src/app/themes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/unauthorized/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unauthorized">> = Specific
  const handler = {} as typeof import("../../src/app/unauthorized/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/owner">> = Specific
  const handler = {} as typeof import("../../src/app/owner/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
