var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/mate/write/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__2ffba720._.js")
R.c("server/chunks/ssr/node_modules_8c3db903._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ed0865a8._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/src_daaa8d64._.js")
R.c("server/chunks/ssr/src_app_error_tsx_ef715cc8._.js")
R.c("server/chunks/ssr/src_ec68d808._.js")
R.c("server/chunks/ssr/_5e4ee9d5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__caf1fe9a._.js")
R.c("server/chunks/ssr/_cd591a15._.js")
R.c("server/chunks/ssr/_2ecb40bf._.js")
R.m(95856)
R.m(48958)
module.exports=R.m(48958).exports
