var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/error/403/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__2ffba720._.js")
R.c("server/chunks/ssr/node_modules_8c3db903._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ed0865a8._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/src_daaa8d64._.js")
R.c("server/chunks/ssr/src_app_error_tsx_ef715cc8._.js")
R.c("server/chunks/ssr/src_ec68d808._.js")
R.c("server/chunks/ssr/_5e4ee9d5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__0c8a0d79._.js")
R.c("server/chunks/ssr/_cd591a15._.js")
R.c("server/chunks/ssr/_f227aef5._.js")
R.m(8660)
R.m(50636)
module.exports=R.m(50636).exports
